# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sequence_next', models.IntegerField(default=99)),
                ('registered', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(null=True, upload_to='account_photos/')),
                ('photo_hash', models.CharField(max_length=128, null=True)),
                ('balance_last_updated', models.DateTimeField(null=True)),
                ('degree', models.IntegerField(default=0)),
                ('settlement_countdown', models.DateTimeField(null=True)),
                ('last_position', models.IntegerField(default=0)),
                ('net_votes', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Trust'), (-1, 'Distrust')], default=0)),
                ('matched', models.BooleanField(default=False)),
                ('position', models.IntegerField(null=True)),
                ('expired', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_arrows', to='core.Account')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_arrows', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Txn', 'Transaction'), ('AC', 'ArrowCreation'), ('AE', 'ArrowExpiration'), ('MS', 'MarketSettlement'), ('MST', 'MarketSettlementTransfer'), ('BU', 'BalanceUpdate'), ('CLC', 'ChallengeLinkCreation'), ('CLE', 'ChallengeLinkExpiration'), ('CS', 'ChallengeSettlement'), ('CST', 'ChallengeSettlementTransfer')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='EventCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_previous_hash', models.CharField(max_length=128)),
                ('txn_type', models.CharField(choices=[('Transfer', 'Transfer'), ('Registration', 'Registration'), ('ChangeVote', 'ChangeVote'), ('Challenge', 'Challenge'), ('ChangeChallengeVote', 'ChangeChallengeVote'), ('Revealation', 'Revealation'), ('Commitement', 'Commitement')], max_length=20)),
                ('sender_seq_no', models.IntegerField()),
                ('txn_message', models.CharField(max_length=328)),
                ('signature', models.CharField(max_length=128)),
                ('txn_data', models.CharField(max_length=1328)),
                ('txn_hash', models.CharField(max_length=128)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TxnCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_txn_no', models.IntegerField()),
            ],
        ),
    ]
