# Generated by Django 2.2.1 on 2019-07-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='chalenges_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='key',
        ),
    ]
