# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-12 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrowUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrowupdate', models.CharField(choices=[('N', 'neutral'), ('T', 'trust'), ('D', 'distrust')], max_length=1)),
                ('arrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arrow')),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Txn')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('photo_hash', models.CharField(max_length=128)),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Txn')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_recieved', to='core.Account')),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Txn')),
            ],
        ),
    ]
