# Generated by Django 2.2.1 on 2019-07-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190704_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='txn',
            name='txn_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Commitment', 'Commitment'), ('Revealation', 'Revealation'), ('Register', 'Register'), ('ChangeVote', 'ChangeVote'), ('Challenge', 'Challenge'), ('ChangeChallengeVote', 'ChangeChallengeVote')], max_length=20),
        ),
    ]
