# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-14 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arrowupdate_registration_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TxnCounter',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance_last_updated',
            new_name='running_balance_last_updated',
        ),
    ]
