# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190514_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
