# Generated by Django 2.2.1 on 2019-07-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190705_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengelink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Support'), (-1, 'Oppose')], default=0),
        ),
        migrations.AlterField(
            model_name='challengelink',
            name='status_who',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Account1'), (-1, 'Account2')], default=0),
        ),
        migrations.CreateModel(
            name='ChallengeLinkUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengelinkupdate', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Trust'), (-1, 'Distrust')])),
                ('challengelink_who_update', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Account1'), (-1, 'Account1')])),
                ('challengelink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengelinkupdate_set', to='core.ChallengeLink')),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Txn')),
            ],
        ),
    ]
