# Generated by Django 2.2.1 on 2019-07-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190709_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Challenge')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='challengelink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Trust'), (-1, 'Distrust')], default=0),
        ),
        migrations.CreateModel(
            name='ChallengeSettlementTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('challenge_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ChallengeSettlement')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
    ]
