# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190514_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ubidue',
            new_name='balance_due',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ubidue_last_updated',
        ),
        migrations.AddField(
            model_name='account',
            name='balance_due_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='sequence_next',
            field=models.IntegerField(default=1),
        ),
    ]
