# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190514_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
    ]
