# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-01 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190531_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='committed_value',
            new_name='committed_hash',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='committed_value',
            new_name='committed_hash',
        ),
    ]
