# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190601_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='committed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
