# Generated by Django 2.2.1 on 2019-07-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_challengecreation_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengelink',
            name='expired',
        ),
    ]
