# Generated by Django 2.2.1 on 2019-06-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_account_committed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrowupdate',
            name='arrowupdate',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Trust'), (-1, 'Distrust')]),
        ),
        migrations.AlterField(
            model_name='revelation',
            name='commitment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revelation', to='core.Commitment'),
        ),
    ]
