# Generated by Django 2.2.1 on 2019-06-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190612_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSettlementTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
                ('market_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MarketSettlement')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ArrowCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Arrow')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
    ]
