# Generated by Django 2.2.1 on 2019-06-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_arrowcreation_marketsettlement_marketsettlementtransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='verified',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_due_last_updated',
            field=models.DateTimeField(),
        ),
    ]
