# Generated by Django 2.2.1 on 2019-06-22 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190616_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('degree', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('settlement_countdown', models.DateTimeField(null=True)),
                ('last_position', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('last_position_who', models.IntegerField(default=0)),
                ('net_votes_who', models.IntegerField(default=0)),
                ('matched_count_who', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_due_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ChallengeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'neutral'), (1, 'support'), (-1, 'oppose')], default=0)),
                ('matched', models.BooleanField(default=False)),
                ('position', models.IntegerField(null=True)),
                ('status_who', models.IntegerField(choices=[(0, 'neutral'), (1, 'd1good'), (-1, 'd2good')], default=0)),
                ('matched_who', models.BooleanField(default=False)),
                ('position_who', models.IntegerField(null=True)),
                ('expired', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengelinks', to='core.Challenge')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengelinks', to='core.Account')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_created', to='core.Account'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='defendant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_against_1', to='core.Account'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='defendant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_against_2', to='core.Account'),
        ),
    ]
