# Generated by Django 2.2.1 on 2019-06-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190622_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengecreations_against_1', to='core.Account')),
                ('defendant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengecreations_against_2', to='core.Account')),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Txn')),
            ],
        ),
    ]
