# Generated by Django 2.2.1 on 2019-07-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190719_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='offer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
