# Generated by Django 2.2.1 on 2019-08-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190724_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrow',
            name='has_new_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='offer',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
