# Generated by Django 2.2.1 on 2019-06-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_challengecreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chalenges_degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='chalenges_key',
            field=models.DecimalField(decimal_places=999, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='degree',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChallengeLinkCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengelink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ChallengeLink')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
    ]
