# Generated by Django 2.2.1 on 2019-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190801_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengelink',
            name='has_new_message',
            field=models.BooleanField(default=False),
        ),
    ]
