# Generated by Django 2.2.1 on 2019-06-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190622_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengelink',
            name='created',
        ),
    ]
