# Generated by Django 2.2.1 on 2019-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_challengelink_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='net_votes',
            field=models.IntegerField(default=0),
        ),
    ]
