# Generated by Django 2.2.1 on 2019-08-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190802_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
