# Generated by Django 2.2.1 on 2019-11-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190808_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_photo',
            field=models.BooleanField(default=True),
        ),
    ]
